### ISSUE TITLE
Ensure that we are checking field accesses

### ISSUE THREAD

**Issue by khatchad** [khatchad/Migrate-Skeletal-Implementation-to-Interface-Refactoring#122]
Ensure that we are allowing source methods to be migrated that access fields available to the interface.

**Comment by khatchad** [comment]
@mdarefin Can you take this one? It might be worth going through the existing tests to see if any source methods legal access fields. Then, check to see if those tests are passing.

**Comment by mdarefin** [comment]
@khatchad sure sound good

**Comment by khatchad** [comment]
Seems related to #141.

**Comment by mdarefin** [comment]
when accessing the same class interface getting to the public field and converting abstract method to default method with a method body getting access to the Sys.out field 

```
package p;

interface I{
	 default void m() {
		System.out.println("Testing");
	}
	 
}

interface J{
	default void n() {
		System.out.println("Testing");
	}
}

abstract public class C implements I,J{
	
}
```

**Comment by mdarefin** [comment]
@khatchad 
I was creating a JUnit test this pass when running the plugin and testing in the running platform, however I create a JUnit test it's failing, not sure why 

```
//testing method at 
public void testInterfaceFieldAccess() throws Exception {
		// This should access the field inside the method  
		helperPass(new String[] { "m" }, new String[][] { new String[0] });
	}
```
testing code
```
package p;

interface I {
	void m();
}

abstract class A implements I {
	public void m() {
		System.out.println("This is working");
	}
}

```

**Comment by khatchad** [comment]
@mdarefin Is this an existing test?

**Comment by mdarefin** [comment]
no, I write the test

**Comment by khatchad** [comment]
Can you go through the existing tests to see if any source methods have legal accesses to fields. Then, check to see if those tests are passing? The tests might be named something like `testMethodThatAccessesField`...

**Comment by mdarefin** [comment]
sure

**Comment by mdarefin** [comment]
I see test for 
```
testMethodThatAccessesType
```
No test for 
```
testMethodThatAccessesField
```

**Comment by khatchad** [comment]
OK, please keep searching.

**Comment by khatchad** [comment]
@mdarefin Any luck?

**Comment by mdarefin** [comment]
I see
```
 testMethodContainedInTypeWithField
 test code:
 package p;

interface I {
	void m();
}

public abstract class A implements I {
	
	static class B {
		private static final int f = 5;
	}

	@Override
	public void m() {
		int f2 = B.f;
	}
}
```

**Comment by khatchad** [comment]
Does that pass or fail? I think it should fail. Do you see why?

**Comment by khatchad** [comment]
Also, for your test with `System.out`, what was the error message? In fact, you could check the tests for source methods that include `System.out` and see if they pass.

**Comment by mdarefin** [comment]
The above test code pass, 
I get no such a file Exception
I am checking the file path to see if I made any speeling error

**Comment by khatchad** [comment]
That example looks like to be from `testMethodContainedInTypeWithField10()`, which is failing case.

**Comment by mdarefin** [comment]
yes, my bad, it's failing

**Comment by khatchad** [comment]
No problem. I think we're good here. We can close.

**Comment by khatchad** [comment]
We are allowing accessible fields.

**Comment by khatchad** [comment]
Thanks, @mdarefin.
