### ISSUE TITLE
How often are we failing for missing run time target check?

### ISSUE THREAD

**Issue by khatchad** [khatchad/Migrate-Skeletal-Implementation-to-Interface-Refactoring#142]
How often is this happening? https://github.com/khatchad/Migrate-Skeletal-Implementation-to-Interface-Refactoring/blob/61b7c550c9b2eb86f4c8e5f7859e98f69fd35d24/edu.cuny.citytech.defaultrefactoring.core/src/edu/cuny/citytech/defaultrefactoring/core/refactorings/MigrateSkeletalImplementationToInterfaceRefactoringProcessor.java#L414

**Comment by khatchad** [comment]
@mdarefin could you take a look at this? You just need to count the number of times that return statement executes. You can use the Colt subject.

**Comment by khatchad** [comment]
Just hit this in a test case!

**Comment by mdarefin** [comment]
Ok, I'm working on it now.

**Comment by khatchad** [comment]
@mdarefin Yes, that's what I meant. But, I'm working on this one now after all because it's skewing the results. Is there something else you can work on?

**Comment by khatchad** [comment]
Strange. I just now received this notification.

On Thu, Apr 28, 2016 at 02:11:27PM -0700, W@LiD wrote:
> Ok, I'm working on it now.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub*
> 

-- 
Raffi Khatchadourian, PhD
Assistant Professor and Open Educational Resources (OER) Fellow
Computer Systems Technology
New York City College of Technology
City University of New York
300 Jay St., Room N913
Brooklyn, NY 11201-1909
United States
+1 (718) 260-5325
rkhatchadourian@citytech.cuny.edu
http://cuny.is/khatchad

**Comment by khatchad** [comment]
It would still be interesting to know how many failures this accounts for but I should have a fix for it soon.

**Comment by mdarefin** [comment]
cool, then I will focus on #115

**Comment by khatchad** [comment]
Thanks @mdarefin.

**Comment by khatchad** [comment]
No need to count. I fixed it, though I don't know what I was concerned about regarding a run time target check. I don't see how the run time target of the method being migrated could change.
