### ISSUE TITLE
Record destination interface in migratable methods table

### ISSUE THREAD

**Issue by khatchad** [khatchad/Migrate-Skeletal-Implementation-to-Interface-Refactoring#146]
We also need the destination interface inferred by the tool to be added to this table. Check out: 
https://github.com/khatchad/Migrate-Skeletal-Implementation-to-Interface-Refactoring/blob/master/edu.cuny.citytech.defaultrefactoring.eval/src/edu/cuny/citytech/defaultrefactoring/eval/handlers/EvaluateMigrateSkeletalImplementationToInterfaceRefactoringHandler.java#L67

The reason is that, when we compare the manually verified results with those of the tool, we also need to compare the destination interfaces. For example, our tool may say that a particular method is migratable but migrate it to the incorrect interface.

**Comment by khatchad** [comment]
@Liv-ee Could you have a look at this one? It's quite similar to the find candidates class you've been working on. Please let me know if you have any questions.

**Comment by khatchad** [comment]
@Liv-ee Any questions on this one?

**Comment by Liv-ee** [comment]
Just clarifying, you mean the interface that you the method moved to correct?

**Comment by khatchad** [comment]
You got it. Because we want to make sure that would have been the interface that an expert, human programmer would have moved the method to. Make sense?

On Thu, Apr 28, 2016 at 10:41:42AM -0700, Olivia Moore wrote:
> Just clarifying, you mean the interface that you the method moved to correct?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub*
> 

-- 
Raffi Khatchadourian, PhD
Assistant Professor and Open Educational Resources (OER) Fellow
Computer Systems Technology
New York City College of Technology
City University of New York
300 Jay St., Room N913
Brooklyn, NY 11201-1909
United States
+1 (718) 260-5325
rkhatchadourian@citytech.cuny.edu
http://cuny.is/khatchad

**Comment by Liv-ee** [comment]
Great I understand thank you.

**Comment by khatchad** [comment]
No problem.

On Thu, Apr 28, 2016 at 10:48:03AM -0700, Olivia Moore wrote:
> Great I understand thank you.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub*
> 

-- 
Raffi Khatchadourian, PhD
Assistant Professor and Open Educational Resources (OER) Fellow
Computer Systems Technology
New York City College of Technology
City University of New York
300 Jay St., Room N913
Brooklyn, NY 11201-1909
United States
+1 (718) 260-5325
rkhatchadourian@citytech.cuny.edu
http://cuny.is/khatchad
