### ISSUE TITLE
CSV file of methods

### ISSUE THREAD

**Issue by khatchad** [khatchad/Migrate-Skeletal-Implementation-to-Interface-Refactoring#34]
I think it may be helpful to also have a table of methods. That way, we can eliminate classes that extend interfaces that have no methods (e.g., `java.io.Serializable`). There may also be some other uses. One thing that makes me hesistant, however, is that we can also use the JDT to find out this information as opposed to a SQL query. What do you think, @mdarefin?

**Comment by khatchad** [comment]
@Liv-ee This is what we have discussed today, I believe. Can you please review?

**Comment by khatchad** [comment]
Plan:

1. Get rid of last comma ("only print a comma when we're not at the last iteration").
1. Instead of printing to the console, store in a variable. Either use a `StringBuilder` or just a `String` but preferably `StringBuilder`.
1. Create a separate `methods.csv` file (Method identifier | Declaring Type FQN).
1. Deal with the parameter comma problem.

**Comment by khatchad** [comment]
@Liv-ee Please issue a [pull request](https://help.github.com/articles/using-pull-requests) once you have committed your changes.

**Comment by Liv-ee** [comment]
Yes I did.

**Comment by khatchad** [comment]
@Liv-ee are we done with this one?

**Comment by Liv-ee** [comment]
Yes we are.

**Comment by khatchad** [comment]
Actually, it looks like the `typesWriter` variable is being issued a `close()` rather than `typesPrinter`. Can you check it out? https://github.com/khatchad/Migrate-Skeletal-Implementation-to-Interface-Refactoring/blob/master/edu.cuny.citytech.defaultrefactoring.eval/src/edu/cuny/citytech/defaultrefactoring/eval/handlers/FindCandidateSkeletalImplementationsHandler.java#L163.

**Comment by Liv-ee** [comment]
You're right. Thanks fixed it.

**Comment by khatchad** [comment]
@Liv-ee can you reference the commit number here?

**Comment by khatchad** [comment]
Alternatively, you can also reference the issue number in the commit. The commit link will then automatically appear here.

**Comment by Liv-ee** [comment]
https://github.com/khatchad/Migrate-Skeletal-Implementation-to-Interface-Refactoring/commit/101882c3d85241d011ecf3725cf0641e8ca1223c
